# Generated by Django 4.2 on 2023-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_settings_remove_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='web_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
