# Generated by Django 4.2 on 2023-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_settings_web_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email_ture',
            field=models.CharField(default='T', max_length=5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='web_name',
            field=models.CharField(default='WebChat', max_length=100),
        ),
    ]
