# Generated by Django 4.2 on 2023-07-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_settings_email_ture_alter_settings_web_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='robot',
            field=models.CharField(default='F', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='super',
            field=models.CharField(default='F', max_length=10),
        ),
    ]
