# Generated by Django 4.2 on 2023-07-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_robot_alter_user_super'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='NO', max_length=100),
        ),
    ]
